imports:
    - { resource: repository.yml }

services:
#    dragonfly_bug_tracker.example:
#        class: Dragonfly\BugTrackerBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]
